### ISSUE TITLE
Automatic generation of `ddcks` for GUI component instances

### ISSUE THREAD

**Issue by zuckerruebe** [SPF-OST/pytrnsys_gui#222]
As a user I'd like the GUI to automatically connect pipes to component instances in the generated `ddck`, i.e. fill in the relevant variable names for the mass flow and temperature at a port to which a pipe is connected.

This meta issue is comprised of the following sub-issues:

- [x] #223 
- [ ] https://github.com/SPF-OST/pytrnsys/issues/94
- [x] https://github.com/SPF-OST/pytrnsys/issues/95
- [ ] @zuckerruebe : create and linke issue here which defines syntax and defines "work package" (unit test which reads in `ddck` with port flow and temps to be replaced and replace them with the corresponding variable names)

**Comment by martin-neugebauer** [comment]
Deprecated through #233
