### ISSUE TITLE
Automatic replacement of placeholder statements when generating ddck files from the GUI

### ISSUE THREAD

**Issue by martin-neugebauer** [SPF-OST/pytrnsys_gui#233]
The newly introduced statements in the form of ``@type(portName, defaultName)``, e.g. ``@temp(hpCondIn, TPiHpCondIn)``, should be correctly replaced with the connection names from the GUI. This requires the completion of a number of subtasks:

- [x] Ensure meaningful port names in the classes of the GUI objects. (@martin-neugebauer  should probably do this)
- [x] Copy an existing example (maybe dualSource, but something else would be better for once) and replace the hydraulic input statements with the new ones featuring the already defined default names and the correct port names as defined in the classes (maybe also a job for @martin-neugebauer)
- [x] #241 
- [x] #243 
- [x] SPF-OST/pytrnsys#101 
- [x] SPF-OST/pytrnsys#102 
- [x] SPF-OST/pytrnsys#103 
- [x] SPF-OST/pytrnsys#106
- [x] SPF-OST/pytrnsys_doc#1

**Comment by martin-neugebauer** [comment]
@zuckerruebe Feel free to extend and adapt

**Comment by martin-neugebauer** [comment]
@zuckerruebe The first tasks is fulfilled by #235, but some tests still have to be adapted for the changes I made. Maybe this is something that @PuaYongHao could on Monday. We also need to deal with #234, a problem which was made worse by the changes I did, but I don't see a way around it. This means we might need some translator that translates diagrams of previous versions to the current one, such that we don't need to redo all diagrams by hand (this wouldn't be popular by many users, I guess.)
