### ISSUE TITLE
Meta item for issues to do with removing dead code.

### ISSUE THREAD

**Issue by zuckerruebe** [SPF-OST/pytrnsys_gui#402]
- [ ] Remove `BlockItem.addTree` method (including all its child implementations). Instead add a plain `QTreeView` with a `QFileSystemModel` (https://doc.qt.io/qt-6/qfilesystemmodel.html#details) as model to the right of the main window: https://github.com/SPF-OST/pytrnsys_gui/issues/377
- [ ] https://github.com/SPF-OST/pytrnsys_gui/issues/193 (might have already been don -> check!)
- [ ] https://github.com/SPF-OST/pytrnsys_gui/issues/110
- [ ] https://github.com/SPF-OST/pytrnsys_gui/issues/213 and https://github.com/SPF-OST/pytrnsys_gui/issues/392
- [ ] https://github.com/SPF-OST/pytrnsys_gui/issues/148
- [ ] https://github.com/SPF-OST/pytrnsys_gui/issues/59
- [ ] https://github.com/SPF-OST/pytrnsys_gui/issues/259
